api:
  build: .
  ports:
   - "3000:3000"
  links:
    - database:db
  environment:
   - GIN_MODE=release
   - DB_USERNAME=postgres
   - DB_PASSWORD=postgres

database:
  build: ../database
  ports:
    - "5432:5432"

importer:
  build: ../importer
  links:
    - database:db
  environment:
   - DB_USERNAME=postgres
   - DB_PASSWORD=postgres
