FROM golang:1.5.2
MAINTAINER Gaël Gillard<gael@gaelgillard.com>

RUN go get github.com/tools/godep

COPY ./files /etc/files
COPY . /go/src/github.com/helphone/api
WORKDIR /go/src/github.com/helphone/api

CMD ["godep", "go", "test", "./..."]
